### ISSUE TITLE
Automate with github actions ?

### ISSUE THREAD

**Issue by Jrchintu** [kaarana/BlockingOrdersByIndianCourts#2]
Is there any possibility that we can utilize github actions to collect daily updates ?

**Comment by srikanthlogic** [comment]
Yes, it should be possible to do that. Its on [TODO](https://github.com/kaarana/BlockingOrdersByIndianCourts#todo) item number 3. Ideally the order doesn't matter - if you can, please send PR

**Comment by Jrchintu** [comment]
> Yes, it should be possible to do that. Its on [TODO](https://github.com/kaarana/BlockingOrdersByIndianCourts#todo) item number 3. Ideally the order doesn't matter - if you can, please send PR

Ok i will try it tomorrow 👍
